// Astrology planet-in-sign influence text
// Keyed by language ('en' / 'uk'), then planet name, then zodiac index 0-11 (Aries … Pisces)
const ASTRO_PLANET_SIGN = {
  en: {
    Mercury: [
      "Sharp, direct mind. Quick decisions, competitive thinking. Enthusiasm for new ideas.",
      "Patient thinker, learns through the senses. Practical and thorough but can be stubborn in views.",
      "At home here — quick-witted, versatile, loves conversation. Tendency to scatter attention.",
      "Intuitive, emotionally driven thinking. Strong memory; logic coloured by feeling.",
      "Creative, expressive, proud in speech. Natural storyteller; can be dramatic in communication.",
      "Analytical and precise. Excellent at detail, criticism, and systematic problem-solving.",
      "Diplomatic, seeks balanced views. Weighs pros and cons; indecision possible.",
      "Probing, intense thought. Penetrating insight; keeps secrets, drawn to hidden matters.",
      "Expansive philosopher. Optimistic, broad-minded, love of travel and higher learning.",
      "Strategic and disciplined. Thinks long-term, values tradition and practical results.",
      "Original, rebellious ideas. Progressive thinking; humanitarian and unconventional.",
      "Imaginative, intuitive, sometimes vague. Absorbs impressions rather than analysing them.",
    ],
    Venus: [
      "Bold in love, direct pursuit. Excitement and novelty valued over security.",
      "Sensual, loyal, steadfast. Enjoys beauty, comfort, and lasting partnerships.",
      "Flirtatious and witty. Loves variety; needs intellectual connection in relationships.",
      "Nurturing, devoted, home-oriented. Emotional depth; family bonds are paramount.",
      "Warm, generous, loves grandly. Dramatic in romance; loyalty and admiration key.",
      "Refined, modest, quality-focused. Nitpicky in love; values practical care and devotion.",
      "Harmonious, beauty-seeking. Natural charm; partnerships and fairness are central.",
      "Intense, transformative bonds. Deep desire and potential jealousy; all-or-nothing.",
      "Freedom-loving adventurer. Philosophical connection valued; resists possessiveness.",
      "Reserved, loyal, status-aware. Shows love through responsibility and long-term commitment.",
      "Unconventional, friendship-based. Values independence; drawn to progressive partners.",
      "Romantic, dreamy, self-sacrificing. Spiritual love; susceptible to idealisation.",
    ],
    Mars: [
      "Powerful, fearless, pioneering. Thrives on challenge; can be impulsive and combative.",
      "Slow to anger but unstoppable once aroused. Tenacious, practical, sensual drive.",
      "Active mind as drive; multitasks energetically. Variable stamina, debate-loving.",
      "Protective, moody energy. Motivated by security and family; indirect but persistent.",
      "Bold, creative, proud action. Natural leader; dramatic expression of willpower.",
      "Precise, hard-working drive. Motivated by improvement and effectiveness; self-critical.",
      "Driven toward fairness; can avoid direct confrontation. Social energy, strategic.",
      "Relentless, intense power. Magnetic sexuality; strategic and uncompromising.",
      "Enthusiastic, freedom-seeking action. Philosophical goals; loves adventure and risk.",
      "Disciplined, ambitious, patient. Long-range vision; persistent climb toward mastery.",
      "Erratic but inventive energy. Progressive rebelliousness; humanitarian goals.",
      "Elusive, sensitive, compassionate drive. Motivated by empathy; energy fluctuates.",
    ],
    Jupiter: [
      "Bold optimism, entrepreneurial spirit. Luck through courage and initiating new ventures.",
      "Abundance through persistence and tangible effort. Enjoys material security and nature.",
      "Expansive intellect, luck through communication. Benefits from teaching and learning.",
      "Growth through emotional nurturing. Home, family, and protective instincts are amplified.",
      "Generous, theatrical optimism. Luck through creativity, children, romance, performance.",
      "Growth via service and practical skill. Benefits from health, analysis, and diligent work.",
      "Expansion through diplomacy and partnership. Luck in relationships and the arts.",
      "Deep transformative growth. Luck through investigation, shared resources, psychology.",
      "At home here — broad wisdom and adventure. Luck through travel, philosophy, and teaching.",
      "Growth through ambition and structure. Success via discipline, career, and authority.",
      "Humanitarian expansion. Luck through groups, technology, and progressive ideals.",
      "Spiritual and artistic growth. Luck through compassion, imagination, and solitude.",
    ],
    Saturn: [
      "Discipline applied to new beginnings. Lessons in courage, independence, and patience.",
      "Rewards slow, steady material effort. Tests stubbornness; builds lasting resources.",
      "Mental discipline required. Communication structured but sometimes over-cautious.",
      "Emotional responsibility, family duty. Inner security must be earned through effort.",
      "Lessons in humility and creative discipline. Pride tested; long-term creative commitment.",
      "Exalted here — mastery through meticulous work. Health, routine, and precision rewarded.",
      "Challenges in relationships and fairness. Karmic partnerships; balance demanded.",
      "Intense karmic transformation. Control tested; deep psychological pruning.",
      "Restricts easy optimism; demands earned wisdom. Travel and philosophy require structure.",
      "At home here — authority through hard work. Career success via patience and integrity.",
      "Discipline applied to society and progress. Innovations tested for long-term value.",
      "Hidden restrictions, spiritual discipline. Isolation can be productive; escapism challenged.",
    ],
    Uranus: [
      "Sudden, energetic reinvention. Revolutionary impulse; breaks old patterns dramatically.",
      "Disrupts comfort and tradition. Change comes to material values and routines.",
      "Lightning-fast communication changes. Mental revolutions; technology and media.",
      "Upsets domestic norms. Unconventional family structures; emotional breakthroughs.",
      "Creative rebellion, dramatic originality. Genius in arts and self-expression.",
      "Revolutionises work and health. Sudden changed routines; innovative methodology.",
      "Disrupts social norms in partnerships. Progressive relationships; equality demanded.",
      "Deep psychological upheaval. Sudden power shifts; transformation of hidden structures.",
      "Liberates philosophy and travel. New world-views arrive suddenly; freedom from dogma.",
      "Breaks traditional authority. Career upheaval; institutions reimagined.",
      "At home here — collective awakening. Technology, human rights, radical innovation.",
      "Dissolves spiritual boundaries. Intuition amplified; dreams and imagination shaken.",
    ],
    Neptune: [
      "Mystical impulse drives action. Idealism in leadership; sacrifice for a vision.",
      "Spiritual connection to earth and senses. Dissolves materialism; artistic appreciation.",
      "Imagination in thought and speech. Inspiration, but confusion or deception possible.",
      "Heightened emotional intuition and empathy. Family idealism; spiritual home life.",
      "Romantic, artistic transcendence. Creative genius; risk of illusion in love.",
      "Idealistic service and healing. Dissolves boundaries of analysis; spiritual health.",
      "Idealises relationships and beauty. Romantic illusion common; longing for union.",
      "At home in depth and mystery. Powerful psychic undertow; intense spiritual renewal.",
      "Spiritual quest through travel and philosophy. Dissolves cultural boundaries.",
      "Dissolves authority and tradition. Spiritual career; structures erode slowly.",
      "Collective spiritual idealism. Humanitarian dreams; shared illusions.",
      "At home here — boundless imagination. Deep psychic sensitivity; compassionate transcendence.",
    ],
    Earth: [
      "Energetic, pioneering year. Bold actions bring results; impulsive decisions tempered.",
      "Grounding stability, productivity. Material achievements; sensory pleasures favoured.",
      "Busy, communicative period. Learning, short journeys, ideas flow freely.",
      "Emotional focus on home and roots. Intuition strong; nurture yourself and others.",
      "Creative spotlight. Romance, play, and self-expression bring fulfilment.",
      "Attention to health and detail. Productive routines; practical improvements rewarded.",
      "Social harmony emphasised. Relationships flourish; balance between self and others.",
      "Deep transformation. Hidden matters surface; personal power is tested and renewed.",
      "Expansive horizons. Travel, learning, and philosophy bring optimism.",
      "Ambition and discipline rewarded. Career achievements; long-term planning pays off.",
      "Innovation and group action. Progressive ideas; community and friendship highlighted.",
      "Intuition and imagination strong. Rest, creativity, and spiritual insight benefit.",
    ],
  },
  uk: {
    Mercury: [
      "Гострий, прямий розум. Швидкі рішення, конкурентне мислення. Ентузіазм до нових ідей.",
      "Терплячий мислитель, вчиться через відчуття. Практичний і ретельний, але може бути впертим.",
      "Як вдома — кмітливий, різносторонній, любить спілкування. Схильність розпорошувати увагу.",
      "Інтуїтивне, емоційно забарвлене мислення. Сильна пам'ять; логіка пронизана почуттям.",
      "Творчий, виразний, гордовитий у мові. Природний оповідач; схильний до драматизму.",
      "Аналітичний і точний. Чудово справляється з деталями, критикою та систематизацією.",
      "Дипломатичний, шукає збалансованих поглядів. Зважує «за» і «проти»; можлива нерішучість.",
      "Пронизливе інтенсивне мислення. Глибоке проникнення в суть; зберігає таємниці.",
      "Широкий філософський погляд. Оптимістичний, широкий кругозір; любить подорожі й навчання.",
      "Стратегічний і дисциплінований. Мислить на перспективу; цінує традицію і практичний результат.",
      "Оригінальні, бунтарські ідеї. Прогресивне мислення; гуманізм і нетрадиційність.",
      "Уявне, інтуїтивне, іноді нечітке. Вбирає враження, а не аналізує.",
    ],
    Venus: [
      "Сміливе, пряме кохання. Новизна й збудження понад стабільність.",
      "Чуттєва, вірна, стійка. Насолоджується красою, затишком і тривалими стосунками.",
      "Кокетлива й дотепна. Любить різноманітність; потрібен інтелектуальний зв'язок.",
      "Дбайлива, відданна, орієнтована на дім. Емоційна глибина; сім'я понад усе.",
      "Тепла, щедра, любить по-великому. Драматична у романтиці; лояльність і захоплення — ключові.",
      "Вишукана, скромна, орієнтована на якість. Прискіплива в коханні; практична турбота.",
      "Гармонійна, прагне краси. Природний шарм; партнерство і справедливість у центрі.",
      "Інтенсивні, трансформуючі зв'язки. Глибоке бажання і можлива ревнощі; все або нічого.",
      "Волелюбна пригодниця. Цінує філософський зв'язок; опирається власництву.",
      "Стримана, вірна, статусна. Виявляє любов через відповідальність і довгострокові зобов'язання.",
      "Нетрадиційна, базована на дружбі. Цінує незалежність; приваблює прогресивних партнерів.",
      "Романтична, мрійлива, самовіддана. Духовне кохання; схильна до ідеалізації.",
    ],
    Mars: [
      "Потужний, безстрашний, першопрохідець. Процвітає в умовах виклику; може бути імпульсивним.",
      "Повільно гніваться, але нестримний. Наполегливий, практичний, чуттєва енергія.",
      "Активний розум як рушій; енергійно виконує кілька справ. Мінлива витривалість.",
      "Захисна, мінлива енергія. Мотивований безпекою і сім'єю; непрямий, але наполегливий.",
      "Смілива, творча, горда дія. Природний лідер; яскравий вияв сили волі.",
      "Точний, працьовитий. Мотивований покращенням і ефективністю; самокритичний.",
      "Прагне справедливості; уникає прямого протистояння. Соціальна енергія, стратегічний.",
      "Невпинна, інтенсивна сила. Магнетична сексуальність; стратегічний і безкомпромісний.",
      "Ентузіастична, свободолюбна дія. Філософські цілі; любить пригоди й ризик.",
      "Дисциплінований, амбітний, терплячий. Далекосяжне бачення; наполегливий шлях до майстерності.",
      "Хаотична, але винахідлива енергія. Прогресивний бунт; гуманістичні цілі.",
      "Невловимий, чутливий, співчутливий рух. Мотивований емпатією; енергія коливається.",
    ],
    Jupiter: [
      "Сміливий оптимізм, підприємницький дух. Удача через хоробрість і нові починання.",
      "Достаток через наполегливість і реальні зусилля. Насолоджується матеріальною безпекою.",
      "Широкий інтелект, удача через спілкування. Вигода від навчання і викладання.",
      "Зростання через емоційну турботу. Дім, сім'я і захисні інстинкти посилюються.",
      "Щедрий, театральний оптимізм. Удача через творчість, дітей, романтику і виступи.",
      "Зростання через служіння і практичні навички. Здоров'я, аналіз і ретельна праця.",
      "Розширення через дипломатію і партнерство. Удача у стосунках і мистецтві.",
      "Глибоке трансформуюче зростання. Удача через дослідження, спільні ресурси, психологію.",
      "Як вдома — широка мудрість і пригоди. Удача через подорожі, філософію і навчання.",
      "Зростання через амбіції і структуру. Успіх завдяки дисципліні, кар'єрі й авторитету.",
      "Гуманістичне розширення. Удача через групи, технології та прогресивні ідеали.",
      "Духовне й художнє зростання. Удача через співчуття, уяву і усамітнення.",
    ],
    Saturn: [
      "Дисципліна на новому старті. Уроки хоробрості, незалежності і терпіння.",
      "Нагороджує повільні, стійкі матеріальні зусилля. Перевіряє впертість; будує ресурси.",
      "Потрібна розумова дисципліна. Спілкування структуроване, але іноді надто обережне.",
      "Емоційна відповідальність, сімейний обов'язок. Внутрішня безпека здобувається зусиллями.",
      "Уроки смиренності й творчої дисципліни. Гордість перевіряється; тривале творче зобов'язання.",
      "Екзальтований тут — майстерність через ретельну роботу. Здоров'я, рутина і точність.",
      "Виклики у стосунках і справедливості. Кармічні партнерства; вимагається баланс.",
      "Інтенсивна кармічна трансформація. Контроль перевіряється; глибоке психологічне очищення.",
      "Обмежує легкий оптимізм; вимагає здобутої мудрості. Подорожі й філософія потребують структури.",
      "Як вдома — авторитет через важку роботу. Кар'єрний успіх завдяки терпінню і доброчесності.",
      "Дисципліна заради суспільства і прогресу. Інновації перевіряються на довгострокову цінність.",
      "Приховані обмеження, духовна дисципліна. Усамітнення може бути продуктивним.",
    ],
    Uranus: [
      "Раптове, енергійне переродження. Революційний імпульс; різко ламає старі шаблони.",
      "Руйнує комфорт і традицію. Зміни торкаються матеріальних цінностей і рутини.",
      "Блискавичні зміни у комунікації. Розумові революції; технології й медіа.",
      "Порушує домашні норми. Нетрадиційні сімейні структури; емоційні прориви.",
      "Творчий бунт, яскрава оригінальність. Геніальність у мистецтві й самовираженні.",
      "Революціонізує роботу і здоров'я. Раптові зміни в рутині; інноваційні методи.",
      "Руйнує соціальні норми у партнерстві. Прогресивні стосунки; вимагається рівність.",
      "Глибоке психологічне потрясіння. Раптові зміни влади; трансформація прихованих структур.",
      "Визволяє філософію і подорожі. Нові світогляди з'являються раптово.",
      "Ламає традиційний авторитет. Кар'єрні потрясіння; інститути переосмислюються.",
      "Як вдома — колективне пробудження. Технології, права людини, радикальні інновації.",
      "Розчиняє духовні межі. Інтуїція посилюється; сни й уява струшуються.",
    ],
    Neptune: [
      "Містичний імпульс рухає дійсністю. Ідеалізм у лідерстві; жертва заради бачення.",
      "Духовний зв'язок із землею і відчуттями. Розчиняє матеріалізм; художнє сприйняття.",
      "Уява в думках і мові. Натхнення, але можлива плутанина чи обман.",
      "Підвищена емоційна інтуїція і емпатія. Сімейний ідеалізм; духовне домашнє життя.",
      "Романтична, художня трансцендентність. Творчий геній; ризик ілюзії в коханні.",
      "Ідеалістичне служіння і зцілення. Розчиняє межі аналізу; духовне здоров'я.",
      "Ідеалізує стосунки і красу. Романтична ілюзія; прагнення єднання.",
      "Як вдома у глибині й таємниці. Потужний психічний потяг; духовне оновлення.",
      "Духовний пошук через подорожі й філософію. Розчиняє культурні межі.",
      "Розчиняє авторитет і традицію. Духовна кар'єра; структури поступово руйнуються.",
      "Колективний духовний ідеалізм. Гуманістичні мрії; спільні ілюзії.",
      "Як вдома — безмежна уява. Глибока психічна чутливість; співчутлива трансцендентність.",
    ],
    Earth: [
      "Енергійний, першопрохідницький рік. Сміливі дії приносять результати.",
      "Стабільність і продуктивність. Матеріальні досягнення; задоволення чуттів.",
      "Насичений, комунікативний період. Навчання, короткі подорожі, ідеї вільно течуть.",
      "Емоційний фокус на домі й коренях. Інтуїція сильна; піклуйтеся про себе та інших.",
      "Творчий прожектор. Романтика, гра й самовираження приносять задоволення.",
      "Увага на здоров'ї й деталях. Продуктивна рутина; практичні покращення нагороджуються.",
      "Наголос на соціальній гармонії. Стосунки процвітають; баланс між собою і іншими.",
      "Глибока трансформація. Приховані речі виходять на поверхню; особиста сила перевіряється.",
      "Розширення горизонтів. Подорожі, навчання й філософія приносять оптимізм.",
      "Нагороджуються амбіції й дисципліна. Кар'єрні досягнення; довгострокове планування.",
      "Інновації й групові дії. Прогресивні ідеї; спільнота й дружба у центрі.",
      "Інтуїція й уява сильні. Відпочинок, творчість і духовне осяяння на користь.",
    ],
  },
};
